"""Unit tests for the kabuki analyzer (no network access)."""

import httpx
import pytest

from app import analyzer
from app.analyzer import (
    ProbeResponse,
    ProbeRefusedError,
    InvalidTargetError,
    analyze_target,
    detect_cdn,
    detect_challenges,
    fingerprint_waf,
    normalize_target,
    parse_rate_limit,
    resolve_dns_chain,
)


def make_probe(
    status: int = 200,
    headers: dict | None = None,
    body: str = "",
    cookies: list[str] | None = None,
    elapsed_ms: float = 12.5,
) -> ProbeResponse:
    return ProbeResponse(
        method="GET",
        url="https://example.com/",
        final_url="https://example.com/",
        status_code=status,
        headers={k.lower(): v for k, v in (headers or {}).items()},
        cookies=cookies or [],
        body=body,
        elapsed_ms=elapsed_ms,
    )


# ── target normalization ─────────────────────────────────────────────────────


def test_normalize_target_adds_scheme():
    assert normalize_target("example.com") == "https://example.com"
    assert normalize_target("http://example.com/a?b=1") == "http://example.com/a?b=1"


def test_normalize_target_rejects_unsupported():
    with pytest.raises(InvalidTargetError):
        normalize_target("")
    with pytest.raises(InvalidTargetError):
        normalize_target("ftp://example.com")


# ── WAF signatures ───────────────────────────────────────────────────────────


def test_waf_cloudflare_headers_and_body():
    probe = make_probe(
        status=403,
        headers={"server": "cloudflare", "cf-ray": "8a1b-MAD", "cf-mitigated": "challenge"},
        body='<html><title>Attention Required! | Cloudflare</title></html>',
        cookies=["cf_clearance=abc; Path=/"],
    )
    matches = fingerprint_waf(probe)
    assert matches
    assert matches[0].vendor == "Cloudflare"
    assert matches[0].product == "Cloudflare WAF"
    assert matches[0].confidence == "high"
    assert matches[0].detection_method == "header"
    assert matches[0].blocked is True
    assert "cf-mitigated" in matches[0].evidence


def test_waf_imperva_cookie_detection():
    probe = make_probe(
        status=200,
        headers={"x-cdn": "Incapsula", "x-iinfo": "10-123"},
        cookies=["incap_ses_123=abc; Path=/"],
    )
    matches = fingerprint_waf(probe)
    assert any(item.vendor == "Imperva" for item in matches)


def test_waf_aws_cloudfront():
    probe = make_probe(headers={"x-amz-cf-id": "abc", "x-amz-cf-pop": "MAD50"})
    vendors = [item.vendor for item in fingerprint_waf(probe)]
    assert "Amazon" in vendors
    assert "AWS" not in vendors  # AWS WAF needs its own marker


def test_waf_clean_response_has_no_matches():
    probe = make_probe(headers={"server": "nginx", "content-type": "text/html"})
    assert fingerprint_waf(probe) == []


def test_waf_modsecurity_body_marker():
    probe = make_probe(
        status=403,
        headers={"server": "Apache"},
        body="Not Acceptable! This error was generated by Mod_Security.",
    )
    matches = fingerprint_waf(probe)
    assert any(item.vendor == "ModSecurity" for item in matches)


# ── challenge detection ──────────────────────────────────────────────────────


def test_challenge_js_cloudflare():
    probe = make_probe(
        status=503,
        headers={"server": "cloudflare", "cf-ray": "abc-MAD"},
        body="<html><body>Enable JavaScript and cookies to continue jschl-answer</body></html>",
    )
    challenges = detect_challenges([probe])
    assert len(challenges) == 1
    assert challenges[0].kind == "js_challenge"
    assert "challenge-platform" in challenges[0].bypass_indicators
    assert challenges[0].severity_hint == "medium"
    assert challenges[0].status_code == 503
    assert challenges[0].response_time_ms == 12.5


def test_challenge_captcha_markers():
    probe = make_probe(
        status=403,
        body='<div class="g-recaptcha" data-sitekey="xyz"></div>',
    )
    challenges = detect_challenges([probe])
    assert challenges[0].kind == "captcha"
    assert "captcha_sitekey_present" in challenges[0].bypass_indicators


def test_challenge_clean_page_is_ignored():
    probe = make_probe(body="<html><body>hello world</body></html>")
    assert detect_challenges([probe]) == []


def test_challenge_ignores_marketing_mentions_on_200():
    probe = make_probe(
        status=200,
        body=(
            "<html><footer>DDoS protection by Cloudflare. Learn about captcha and "
            "web application firewall products.</footer></html>"
        ),
    )
    assert detect_challenges([probe]) == []


def test_challenge_captcha_artifact_on_200():
    probe = make_probe(status=200, body='<div class="g-recaptcha" data-sitekey="k"></div>')
    challenges = detect_challenges([probe])
    assert challenges[0].kind == "captcha"


def test_waf_ignores_generic_x_served_by():
    probe = make_probe(headers={"x-served-by": "marketing-site"})
    vendors = [item.vendor for item in fingerprint_waf(probe)]
    assert "Fastly" not in vendors


def test_waf_fastly_cache_node_is_matched():
    probe = make_probe(headers={"x-served-by": "cache-mad12423-MAD"})
    vendors = [item.vendor for item in fingerprint_waf(probe)]
    assert "Fastly" in vendors


def test_challenge_block_page_403():
    probe = make_probe(status=403, body="Access Denied - request blocked by WAF")
    challenges = detect_challenges([probe])
    assert challenges[0].kind == "block_page"
    assert challenges[0].severity_hint == "high"


# ── rate limit parsing ───────────────────────────────────────────────────────


def test_rate_limit_standard_headers():
    probe = make_probe(
        headers={"ratelimit-limit": "100", "ratelimit-policy": "100;w=60", "ratelimit-remaining": "99"}
    )
    profile = parse_rate_limit(probe)
    assert profile.limit == 100
    assert profile.window_seconds == 60
    assert profile.scope == "ip"
    assert profile.recommended_delay_ms == 1200  # (60*1000/100)*2
    assert profile.threshold_estimate is None


def test_rate_limit_legacy_headers_and_retry_after():
    probe = make_probe(
        status=429,
        headers={
            "x-ratelimit-limit": "30",
            "x-ratelimit-window": "60",
            "retry-after": "45",
        },
    )
    profile = parse_rate_limit(probe, probes=[probe], aborted=True)
    assert profile.limit == 30
    assert profile.window_seconds == 60
    assert profile.recommended_delay_ms == 45000
    assert profile.threshold_estimate == 0  # no successful probe before the abort


def test_rate_limit_absent_uses_conservative_default():
    profile = parse_rate_limit(make_probe())
    assert profile.scope == "unknown"
    assert profile.limit is None
    assert profile.recommended_delay_ms == 2000
    assert profile.headers == {}


# ── CDN detection ────────────────────────────────────────────────────────────


def test_cdn_cloudflare_with_edge_nodes_and_cache():
    probe = make_probe(
        headers={"cf-ray": "8a1b2c-MAD", "cf-cache-status": "HIT", "server": "cloudflare"}
    )
    cdn = detect_cdn(probe, dns_info={"cnames": ["edge.example.com"], "addresses": ["203.0.113.7"]})
    assert cdn is not None
    assert cdn.provider == "Cloudflare"
    assert "pop:MAD" in cdn.edge_nodes
    assert "edge.example.com" in cdn.edge_nodes
    assert "203.0.113.7" in cdn.edge_nodes
    assert cdn.origin_hidden is True
    assert cdn.caching == "hit"


def test_cdn_tls_issuer_hint():
    probe = make_probe(headers={"server": "nginx"})
    cdn = detect_cdn(probe, tls_info={"issuer_organization": "Cloudflare, Inc."})
    assert cdn is not None
    assert cdn.provider == "Cloudflare"
    assert "tls issuer" in (cdn.evidence or "")


def test_cdn_absent():
    assert detect_cdn(make_probe(headers={"server": "nginx"})) is None


# ── DNS chain ────────────────────────────────────────────────────────────────


class _FakeCname:
    def __init__(self, target: str):
        self.target = target


class _FakeAddress:
    def __init__(self, value: str):
        self._value = value

    def __str__(self) -> str:
        return self._value


class _FakeResolver:
    lifetime = 5.0

    def __init__(self, mapping: dict):
        self.mapping = mapping

    def resolve(self, name: str, rrtype: str):
        value = self.mapping.get((name, rrtype))
        if value is None:
            raise RuntimeError(f"no {rrtype} record for {name}")
        if rrtype == "CNAME":
            return [_FakeCname(item) for item in value]
        return [_FakeAddress(item) for item in value]


def test_resolve_dns_chain_follows_cnames():
    resolver = _FakeResolver(
        {
            ("www.example.com", "CNAME"): ["edge.example.com."],
            ("edge.example.com", "CNAME"): ["cdn.provider.net."],
            ("www.example.com", "A"): ["203.0.113.10"],
        }
    )
    info = resolve_dns_chain("www.example.com", resolver=resolver)
    assert info["cnames"] == ["edge.example.com", "cdn.provider.net"]
    assert info["addresses"] == ["203.0.113.10"]


def test_resolve_dns_chain_never_raises():
    info = resolve_dns_chain("example.com", resolver=_FakeResolver({}))
    assert info == {"cnames": [], "addresses": []}


# ── guardrails ───────────────────────────────────────────────────────────────


@pytest.mark.anyio
async def test_graduated_requires_explicit_confirm():
    with pytest.raises(ProbeRefusedError):
        await analyze_target("https://example.com", probe_mode="graduated", confirm=False)


@pytest.mark.anyio
async def test_max_requests_is_capped():
    with pytest.raises(ProbeRefusedError):
        await analyze_target(
            "https://example.com",
            probe_mode="graduated",
            confirm=True,
            max_requests=analyzer.MAX_MAX_REQUESTS + 1,
        )


@pytest.mark.anyio
async def test_invalid_target_is_rejected():
    with pytest.raises(InvalidTargetError):
        await analyze_target("ftp://example.com")


@pytest.mark.anyio
async def test_graduated_aborts_on_first_429():
    calls = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["count"] += 1
        if calls["count"] >= 2:
            return httpx.Response(
                429,
                headers={"retry-after": "30", "ratelimit-limit": "10", "ratelimit-policy": "10;w=60"},
                text="slow down",
            )
        return httpx.Response(200, headers={"server": "nginx"}, text="ok")

    result = await analyze_target(
        "https://example.com",
        probe_mode="graduated",
        confirm=True,
        max_requests=5,
        transport=httpx.MockTransport(handler),
        resolve_dns=False,
        inspect_tls=False,
        delay_ms=(0, 0),
    )
    assert calls["count"] == 2  # aborted right after the first 429
    assert result["guardrail"]["aborted"] is True
    assert "429" in result["guardrail"]["abort_reason"]
    assert result["guardrail"]["requests_sent"] == 2
    assert result["rate_limit"].threshold_estimate == 1
    assert result["rate_limit"].recommended_delay_ms == 30000
    assert any(challenge.status_code == 429 for challenge in result["challenges"]) is False


@pytest.mark.anyio
async def test_headers_mode_sends_exactly_one_request():
    calls = {"count": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["count"] += 1
        return httpx.Response(200, headers={"server": "nginx"}, text="ok")

    result = await analyze_target(
        "https://example.com",
        transport=httpx.MockTransport(handler),
        resolve_dns=False,
        inspect_tls=False,
    )
    assert calls["count"] == 1
    assert result["guardrail"]["probe_mode"] == "headers"
    assert result["guardrail"]["requests_sent"] == 1


@pytest.mark.anyio
async def test_progress_callback_reports_all_phases():
    phases: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, headers={"server": "nginx"}, text="ok")

    async def on_progress(phase: str, message: str, data=None) -> None:
        phases.append(phase)

    await analyze_target(
        "https://example.com",
        transport=httpx.MockTransport(handler),
        resolve_dns=False,
        inspect_tls=False,
        on_progress=on_progress,
    )
    assert list(dict.fromkeys(phases)) == ["fingerprint", "challenge", "rate_limit", "cdn"]
    assert phases[0] == "fingerprint"
    assert phases[-1] == "cdn"
